### PR TITLE
Add Categories into track files

### LINKED ISSUE #64: Add Category line into track file format
Currently, the tracks are located in a subdirectory based on their category, this means that if you want the track in multiple categories you have to duplicate files. I think we should add category as a field into tracks to remove duplicates.

Just for the reference, from the 3178 tracks currently loaded, there are around 1500 duplicates.

### PR DESCRIPTION
**Pull request by pehala**
* Track files now contain also all categories they reside in.
  * Deprecate and conserve `TrackFileParser` as it can only intentionally handle V1 format.
  * Correct `TrackParser` to use now is `VersionedTrackFileParser `
* Restructure parsers
* Convert existing tracks
   * Reduced from 3700 to 2055
* Add converter CLI option for server
  * `java -jar server.jar convert tracks` - Converts all tracks in place, doesn't override already converted ones.

TODO:
- [x] Documentation
- [x]  Fix tests

Closes #64.

### CODE REVIEW

**Comment by pehala** [comment]
I might do a little polishing but it is definitely review ready

**Comment by PhilippvK** [comment]
@pehala The Server Check failed in the GitHub CI Run.

**Review by PhilippvK — APPROVED** [review]

**Comment by pehala** [comment]
Yep, based on my investigation it is caused by mocking and testing CLI with subcommands. It is a failure in tests not in the funcionality (at least from what I tested :D)

**Comment by PhilippvK** [comment]
Dump question, but are the converted track still in the repo? Can't find them at the moment.

**Comment by pehala** [comment]
They are supposed to be but seems like I forgot to add them. Good catch, Thanks!

**Comment by PhilippvK** [comment]
@pehala How to compile the server.jar with Maven with the failing tests?

**Comment by pehala** [comment]
`mvn install -DskipTests`

**Comment by pehala** [comment]
Tracks added now

**Comment by PhilippvK** [comment]
Okay. Here is my first impression:

1. GREAT WORK
2. The Championships are intentionally broken, right?
3. Was there ever a `Skip track` button in the solo-mode?
4. When testing the multiplayer the clients crashed when both players pressed `Skip`:

```
a500
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at agolf.TrackCollection.addTrack(TrackCollection.java:12)
	at agolf.game.GamePanel.method333(GamePanel.java:288)
	at agolf.Conn.handlePacket(Conn.java:184)
	at agolf.Conn.dataReceived(Conn.java:24)
	at com.aapeli.connection.GamePacketQueue.run(GamePacketQueue.java:32)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pehala** [comment]
* Thanks! Although as you can see there a lot to be done in terms of bugs
* Yes, the championships are broken intentionally, I think they were broken before (based on the code that returned No tracksets on the server :D) but if they werent I need to fix them.
* I don´t know? If it is there, I certainly didn´t add it on purpose.
* Thanks! I will look at it.

**Comment by pehala** [comment]
* Bug with skip fixed
* Also the skip button on singleplayer appears when you are over or close to average par.

**Comment by PhilippvK** [comment]
Impressive contributions!

**Comment by PhilippvK** [comment]
@pehala ready for merge? How about Documentation updates? Does the README already contain information on the Tracks migration?

**Comment by pehala** [comment]
Nope, I still need to fix the testa and add the documentation. I will add the checkboxes into the description.

Btw: What would you like to see in the docs? I could write there the whole structure of the track file and how it is processed but that would be in the separate file

**Comment by PhilippvK** [comment]
@pehala Regarding the docs: I only thought about the essentials on how to get a server running. But I just realized that as all the files are already converted the exact process of migration is not really needed.

Details in the File structure are definitely optional, they also don't have to be in markdown format if you prefer to define them as comments inside the implementation only.

**Comment by pehala** [comment]
I created issue for the mockito/picocli bug remkop/picocli#1243

**Comment by PhilippvK** [comment]
Many thanks!

**Comment by pehala** [comment]
Tests and documentation are now done.

**Pull request merged**
