### PR TITLE
Fix sound, upgrade to Java 17

### PR DESCRIPTION
**Pull request by StenAL**
This restores the satisfying `thunk` sound that plays on every stroke.

See individual commits for more details.

Highlights:
- deobfuscate a decent chunk of code, including most classes related to playing sound
- fix tests on Windows
- upgrade to Java 17
- remove some unused/duplicate resources
- play sounds
  - for the player's strokes
  - for other players' strokes
  - when the player wins/draws/loses a multiplayer game

### CODE REVIEW

**Comment by PhilippvK** [comment]
@StenAL This is awesome. Give me a few days to try it out :)

**Comment by PhilippvK** [comment]
@StenAL Sound works as expected!

However I found out that the game crashes at the end of a singleplayer round:

```
>>> Packet{channel=[id: 0x058bf4fc, /127.0.0.1:54884 => /127.0.0.1:4242], type=DATA, count=112, message='game\tendstroke\t0\tt'}
>>> Packet{channel=[id: 0x058bf4fc, /127.0.0.1:54884 => /127.0.0.1:4242], type=DATA, count=113, message='error-debug\t4\tjava.lang.NullPointerException: Cannot load from int array because "outcome" is null\tgame\end\tgame\startturn\0\tgame\endstroke\0\t'}
>>> Packet{channel=[id: 0x058bf4fc, /127.0.0.1:54884 => /127.0.0.1:4242], type=COMMAND, count=0, message='end'}
Unhandled packet: Packet{channel=[id: 0x058bf4fc, /127.0.0.1:54884 :> /127.0.0.1:4242], type=DATA, count=113, message='error-debug\t4\tjava.lang.NullPointerException: Cannot load from int array because "outcome" is null\tgame\end\tgame\startturn\0\tgame\endstroke\0\t'}
Unhandled packet: Packet{channel=[id: 0x058bf4fc, /127.0.0.1:54884 :> /127.0.0.1:4242], type=COMMAND, count=0, message='end'}
Client disconnected: [id: 0x058bf4fc, /127.0.0.1:54884 :> /127.0.0.1:4242]
```

This does not happen in the `master` branch, aka. it might be related to the Sound changes or Java upgrade. I hope you can reproduce this...

**Comment by StenAL** [comment]
Thanks for the thorough testing! I only tested in multipayer.

I've pushed a fix now, the issue was with trying to play music at the end of a game based on the results, but in a single player game the server does not send any results so there was a null dereference.

**Comment by PhilippvK** [comment]
@StenAL the CI needs a patch to use Java 17 instead of 8. Should I fix this in a followup or can you have a look?

**Comment by StenAL** [comment]
I can take a look and I'll also squash the crash fix commit into the original change.

**Comment by StenAL** [comment]
@PhilippvK Looks like you need to approve every CI run, let's hope the first try works.
image

**Comment by StenAL** [comment]
Alright, looks like CI passed (https://github.com/PhilippvK/playforia-minigolf/actions/runs/4834120524/jobs/8614993225?pr=103).

I've squashed the two fixup commits, the crash fix is now in https://github.com/PhilippvK/playforia-minigolf/pull/103/commits/d7cdeb8d83b8f55414ddd37787814d2a264b409f and CI fix is in https://github.com/PhilippvK/playforia-minigolf/pull/103/commits/dc8b995ff94f73733a450cb8cf97346257431805

**Pull request merged**
